apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: RKE2ControlPlane
metadata:
  name: rke2cp-test
  namespace: webhook-test
spec: 
  replicas: 3
  agentConfig:
    version: v1.24.11+rke2r1
  serverConfig:
    cniMultusEnable: true
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DockerMachineTemplate
    name: controlplane
  nodeDrainTimeout: 2m
