name: E2E tests (self hosted test)
on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: [self-hosted, linux]
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          docker-images: false
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.20.x
      - name: Build e2e image
        run: make e2e-image
      - uses: actions/cache@v4.0.1
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-test-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-test-go-${{ hashFiles('**/go.sum') }}
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.16.0"
          skipClusterCreation: "true"
      - name: Run E2E tests
        run: make test-e2e
      - name: Archive artifacts
        if: always()
        uses: actions/upload-artifact@v4.3.1
        with:
          name: e2e-artifacts
          path: _artifacts
          if-no-files-found: ignore
