name: E2E tests
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19.x
      - name: Build e2e image
        run: make e2e-image
      - uses: actions/cache@v3.3.1
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-test-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-test-go-${{ hashFiles('**/go.sum') }}
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.16.0"
          skipClusterCreation: "true"
      - name: Run E2E tests
        run: make test-e2e
      - name: Archive artifacts
        if: always()
        uses: actions/upload-artifact@v3.1.2
        with:
          name: e2e-artifacts
          path: _artifacts
          if-no-files-found: ignore