name: golangci-lint

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

# Remove all permissions from GITHUB_TOKEN except metadata.
permissions: {}

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory:
          - ""
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.5.0
        with:
          version: v1.50.1
          working-directory: ${{matrix.working-directory}}
          args: --timeout=5m0s
